version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.9-apache-node-browsers
      - image: circleci/mysql
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Migrate Database
          command: php artisan migrate:fresh --force
      - run:
          name: Run Tests
          command: vendor/bin/phpunit
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
